version: '3.8'

services:
  web:
    image: adamrit/djangoproject:latest
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=DjangoProject.settings
      - DATABASE_URL=postgres://django_user:django_password@db:5432/django_db
    depends_on:
      - db
    networks:
      - django_network

  db:
    image: adamrit/postgres:alpine
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - django_network

volumes:
  db_data:

networks:
  django_network:

